
package cs.insure.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.1
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ClaimDataStore", targetNamespace = "http://server.insure.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ClaimDataStore {


    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "size", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.Size")
    @ResponseWrapper(localName = "sizeResponse", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.SizeResponse")
    @Action(input = "http://server.insure.com/ClaimDataStore/sizeRequest", output = "http://server.insure.com/ClaimDataStore/sizeResponse")
    public int size();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocumentsByClaim", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.GetDocumentsByClaim")
    @ResponseWrapper(localName = "getDocumentsByClaimResponse", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.GetDocumentsByClaimResponse")
    @Action(input = "http://server.insure.com/ClaimDataStore/getDocumentsByClaimRequest", output = "http://server.insure.com/ClaimDataStore/getDocumentsByClaimResponse")
    public String getDocumentsByClaim(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "signatureValidation", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.SignatureValidation")
    @ResponseWrapper(localName = "signatureValidationResponse", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.SignatureValidationResponse")
    @Action(input = "http://server.insure.com/ClaimDataStore/signatureValidationRequest", output = "http://server.insure.com/ClaimDataStore/signatureValidationResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://server.insure.com/ClaimDataStore/signatureValidation/Fault/Exception")
    })
    public boolean signatureValidation(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClaimSize", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.GetClaimSize")
    @ResponseWrapper(localName = "getClaimSizeResponse", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.GetClaimSizeResponse")
    @Action(input = "http://server.insure.com/ClaimDataStore/getClaimSizeRequest", output = "http://server.insure.com/ClaimDataStore/getClaimSizeResponse")
    public int getClaimSize(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "claimExistence", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.ClaimExistence")
    @ResponseWrapper(localName = "claimExistenceResponse", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.ClaimExistenceResponse")
    @Action(input = "http://server.insure.com/ClaimDataStore/claimExistenceRequest", output = "http://server.insure.com/ClaimDataStore/claimExistenceResponse")
    public boolean claimExistence(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns cs.insure.client.Claim
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getClaim", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.GetClaim")
    @ResponseWrapper(localName = "getClaimResponse", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.GetClaimResponse")
    @Action(input = "http://server.insure.com/ClaimDataStore/getClaimRequest", output = "http://server.insure.com/ClaimDataStore/getClaimResponse")
    public Claim getClaim(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     * @throws Exception_Exception
     */
    @WebMethod
    @RequestWrapper(localName = "addDocToClaim", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.AddDocToClaim")
    @ResponseWrapper(localName = "addDocToClaimResponse", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.AddDocToClaimResponse")
    @Action(input = "http://server.insure.com/ClaimDataStore/addDocToClaimRequest", output = "http://server.insure.com/ClaimDataStore/addDocToClaimResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://server.insure.com/ClaimDataStore/addDocToClaim/Fault/Exception")
    })
    public void addDocToClaim(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4)
        throws Exception_Exception
    ;

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUuid", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.GetUuid")
    @ResponseWrapper(localName = "getUuidResponse", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.GetUuidResponse")
    @Action(input = "http://server.insure.com/ClaimDataStore/getUuidRequest", output = "http://server.insure.com/ClaimDataStore/getUuidResponse")
    public int getUuid();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "claimToString", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.ClaimToString")
    @ResponseWrapper(localName = "claimToStringResponse", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.ClaimToStringResponse")
    @Action(input = "http://server.insure.com/ClaimDataStore/claimToStringRequest", output = "http://server.insure.com/ClaimDataStore/claimToStringResponse")
    public String claimToString(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "userValidation", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.UserValidation")
    @ResponseWrapper(localName = "userValidationResponse", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.UserValidationResponse")
    @Action(input = "http://server.insure.com/ClaimDataStore/userValidationRequest", output = "http://server.insure.com/ClaimDataStore/userValidationResponse")
    public boolean userValidation(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "claimValidation", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.ClaimValidation")
    @ResponseWrapper(localName = "claimValidationResponse", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.ClaimValidationResponse")
    @Action(input = "http://server.insure.com/ClaimDataStore/claimValidationRequest", output = "http://server.insure.com/ClaimDataStore/claimValidationResponse")
    public boolean claimValidation(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns cs.insure.client.Document
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocumentbyId", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.GetDocumentbyId")
    @ResponseWrapper(localName = "getDocumentbyIdResponse", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.GetDocumentbyIdResponse")
    @Action(input = "http://server.insure.com/ClaimDataStore/getDocumentbyIdRequest", output = "http://server.insure.com/ClaimDataStore/getDocumentbyIdResponse")
    public Document getDocumentbyId(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     * @throws Exception_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createClaim", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.CreateClaim")
    @ResponseWrapper(localName = "createClaimResponse", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.CreateClaimResponse")
    @Action(input = "http://server.insure.com/ClaimDataStore/createClaimRequest", output = "http://server.insure.com/ClaimDataStore/createClaimResponse", fault = {
        @FaultAction(className = Exception_Exception.class, value = "http://server.insure.com/ClaimDataStore/createClaim/Fault/Exception")
    })
    public int createClaim(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1)
        throws Exception_Exception
    ;

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocContent", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.GetDocContent")
    @ResponseWrapper(localName = "getDocContentResponse", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.GetDocContentResponse")
    @Action(input = "http://server.insure.com/ClaimDataStore/getDocContentRequest", output = "http://server.insure.com/ClaimDataStore/getDocContentResponse")
    public String getDocContent(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocUserId", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.GetDocUserId")
    @ResponseWrapper(localName = "getDocUserIdResponse", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.GetDocUserIdResponse")
    @Action(input = "http://server.insure.com/ClaimDataStore/getDocUserIdRequest", output = "http://server.insure.com/ClaimDataStore/getDocUserIdResponse")
    public int getDocUserId(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDocSignature", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.GetDocSignature")
    @ResponseWrapper(localName = "getDocSignatureResponse", targetNamespace = "http://server.insure.com/", className = "cs.insure.client.GetDocSignatureResponse")
    @Action(input = "http://server.insure.com/ClaimDataStore/getDocSignatureRequest", output = "http://server.insure.com/ClaimDataStore/getDocSignatureResponse")
    public String getDocSignature(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
